### ISSUE TITLE
RPD file Generic password is not working

### ISSUE THREAD

**Issue by sataru15** [karthik-kamisetty/oac#1]
Please provide the rpd file "Cost_Usage_OACreports.rpd" password.

**Comment by sataru15** [comment]
Any update?

**Comment by sataru15** [comment]
Can you please provide an update on this?

**Comment by sataru15** [comment]
Please provide the password to access the rpd

**Comment by karthik-kamisetty** [comment]
> Please provide the password to access the rpd

please try Oracle123456
